apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  # Database
  database.url: "jdbc:postgresql://postgres:5432/notificationdb"

  # RabbitMQ
  rabbitmq.host: "rabbitmq"
  rabbitmq.port: "5672"

  # Application
  spring.application.name: "notification-service"