
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'employee-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['employee-service:8081']

  - job_name: 'calendar-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['calendar-service:8082']

  - job_name: 'leave-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['leave-service:8083']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8084']
