apiVersion: v1
kind: ConfigMap
metadata:
  name: leave-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/leavedb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"