apiVersion: v1
kind: ConfigMap
metadata:
  name: calendar-config
  namespace: default
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/calendardb"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"